import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { AccountContextProvider } from "@/components/context";
import { CategoryContextProvider } from "@/components/categoryContext";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import dynamic from "next/dynamic";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const home = dynamic(() => import("./(main)/page"), {
    ssr: true,
    loading: () => <Loading />,
  });
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          {children}
          <ToastContainer />
        </body>
      </AuthProvider>
    </html>
  );
}
